cardPlayed: '{player} plays {card}.'
cardPlayedHiddenBefore: '{player} plays {card} (hidden).'
cardPlayedHiddenThisRound: '{player} plays a card (hidden).'
cardsDealt: '{player} is dealt {number} additional cards.'
endOfGame: The game is over, the final order is {playerRanking}.
playerChosen: '{role}: {player} chooses {playerChosen}.'
pointsAwarded: '{player} won {numberTricks} tricks. Due to their role {role} they
  receive {numberPoints} points.'
roleChosen: '{player} chooses to be {role} for this game.'
roundStartPlayOrder: 'Round {number} starts where the players are ordered as follows:
  {playerList}.'
skipTurn: '{player} skips playing any cards.'
startOfGame: 'Let''s go (ID: {gameId})! We''re playing {numberSubgames} subgames,
  the players {playerList} ({number} in total) are attending. We therefore play with
  {numberCardsTotal} cards, where there are {numberColors} colors where {numberCards}
  is the highest number.'
subgameStarts: The cards for game {number} of {numberTot} are distributed. {card}
  is revealed to be the trump card this time.
trickWon: '{player} wins the trick.'
trumpChosen: '{player} chooses {color} as the new trump color.'
