cardPlayed: '{player} plays {card}.'
roleChosen: '{player} chooses to be {role} for this game.'
roundStartPlayOrder: 'Round {number} starts where the players are ordered as follows:
  {playerList}.'
skipTurn: '{player} skips playing any cards.'
startOfGame: 'Starting a {number}-player game (ID: {gameId}) with {playerList}. We
  therefore play with {numberCardsTotal} cards, where there are {numberColors} colors
  where {numberCards} is the highest number.'
subgameStarts: ''
trickWon: ''
