targets:
    $default:
        builders:
            # json_serializable:
            #     options:
            #         any_map: true
            #         explicit_to_json: true
            tricking_bees|generator:
                enabled: true

builders:
  generator:
    import: "package:tricking_bees/codegen/builders/builder.dart"
    builder_factories: ["generateRouting"]
    build_extensions: { ".dart": [".r.dart"] }
    auto_apply: root_package
    build_to: source
    applies_builders: ["source_gen|combining_builder"]