name: tb_core
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  build:
  cloud_firestore: ^4.17.5
  code_builder: ^4.8.0
  dart_style: ^2.3.6
  json_annotation: ^4.9.0
  meta: ^1.11.0
  source_gen: ^1.4.0
  test: ^1.24.9
  yust: ^3.21.1
  # yust:
  #   path: ../../../yust
  #       # git:
  #       #     url: https://github.com/univelop/yust.git
  #       #     ref: master

dev_dependencies:
    build_runner: ^2.2.0
    json_serializable: ^6.5.4
    lints: ^3.0.0
    matcher: ^0.12.15

