/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
library;

import 'package:flutter/widgets.dart';

/// Custom Icons
class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  /// Icon data for `apple`.
  static const IconData apple =
      IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for `google`.
  static const IconData google =
      IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for `microsoft`.
  static const IconData microsoft =
      IconData(0xf3ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
